#!/usr/bin/env bash
set -euo pipefail

# aevh.conf v1.0 2026-03-29

readonly WINDOZE_VER="2026-04-03"

# Proxies APT cache
readonly APT_PROXIES=(
		"10.115.201.230:3142"
		"10.115.201.231:3142"
	)

# Liga o compositor gráfico Picom
PICOM=1

# Por 1 para ver mensagens de debug
DEBUG=1
