#!/usr/bin/env bash
set -euo pipefail

# aevh.conf v1.0 2026-03-29

# Liga o compositor gráfico Picom
readonly PICOM=1

# Proxies APT cache
readonly APT_PROXIES=(
		"10.115.201.230:3142"
		"10.115.201.231:3142"
	)

# Por 1 para ver mensagens de debug
DEBUG=1
