#!/usr/bin/env bash
set -euo pipefail

# aevh.conf v1.0 2025-12-25

# Liga o modo debug
ICE_DEBUG=0

# Liga o compositor gráfico Picom
PICOM=1

# Subsistema de fala

# Liga a capacidade de 'falar'
ICE_SPEAK=1

# Tempo (décimas de segundo) que espera até função de fala ficar disponível
ICE_SPEAK_WAIT=5

# 'Falar' os logs
ICE_LOG_SPEAK=0

# Ambiente gráfico
AEVH_GUI="XFCE4"

