# picom.conf
backend = "glx";
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
experimental-backends = false;
vsync = true;
use-damage = true

# ==== BLUR ====
#blur: {
#  method = "kernel";
#  kernel = "7x7box";
#}
#blur-background = true;
# Exclui janelas específicas do efeito de desfoque
#blur-background-exclude = [
#    "window_type = 'dock'",
#    "window_type = 'desktop'",
#    "class_g = 'Plank'",
# Exclui menus pop-up, submenus, tooltips e dropdowns
#    "window_type = 'popup_menu'",
#    "window_type = 'dropdown_menu'",
#    "window_type = 'utility'",
#    "window_type = 'tooltip'",
#    "class_g = 'slop'"
#];

# Opacidade global padrão. (0.0 a 1.0)
active-opacity = 1.0;
inactive-opacity = 1.00;
frame-opacity = 0.8;

# Permite que janelas inativas fiquem transparentes.
inactive-dim = 0.0; # 0.0 a 1.0

# ==== FADE ====
fading = true;
fade-delta = 5;
fade-in-step = 0.03;
fade-out-step = 0.03;

# ==== SHADOW ====
# Habilita sombras de janelas.
shadow = true;
shadow-radius = 14;
shadow-offset-x = -12;
shadow-offset-y = -12;
shadow-opacity = 0.35;

# Define quais janelas não devem ter sombra.
shadow-exclude = [
"name = 'Notification'",
    "class_g = 'Conky'",
    "class_g = 'Dmenu'",
    "class_g = 'Plank'",
    "class_g = 'popup'",
    "class_g ?= 'Notify-osd'",
    "_GTK_FRAME_EXTENTS@:c",
    # Evita sombras em janelas arrastadas (melhora performance visual)
    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_HIDDEN'"
];

# ==== CORNER ====
# Define o raio dos cantos arredondados (em pixels).
#corner-radius = 10;
# rounded-corners-exclude = [
#    "window_type = 'dock'",        # Painel/Barra de Tarefas
#    "window_type = 'desktop'",
#    "class_g = 'Dmenu'",
#    "class_g = 'Plank'",
#    "window_type = 'tooltip'",
#    "window_type = 'menu'",
#    "window_type = 'popup_menu'",
#    "window_type = 'dropdown_menu'",
#    # Não arredondar janelas em ecrã inteiro (fullscreen)
#    "_NET_WM_STATE@:32a *= '_NET_WM_STATE_FULLSCREEN'"
#];

