[Seat:*]
greeter-session=slick-greeter
user-session=default
allow-guest=false
greeter-hide-users=false
greeter-show-manual-login=false
#greeter-setup-script=/usr/bin/numlockx on
#display-setup-script=/opt/aevh/bin/monitor-ctrl mirror