[Greeter]
background=/usr/share/backgrounds/Windoze/waves-color.jpg
theme-name=Fluent-round-Light-compact
icon-theme-name=wow64-Light
cursor-theme-name=Adwaita
draw-user-backgrounds=false
show-hostname=true
show-manual-login=false
show-power=true
show-a11y=false
show-clock=true
show-quit=true
show-username=true
show-keyboard=true
activate-numlock=true
clock-format=%H:%M | %a %d %b