#!/bin/bash

# install windoze from network v1.0.1
# 2026-04-02

# wget --no-check-certificate https://files.verdehorizonte.net/api/public/dl/NHXSbLKY/install-windoze-from-network

error() { echo "Oops: $*"; exit 1; }


main() {
      [[ "$EUID" != "0" ]] && error "São necessários provilégios de root"
      win="windoze.tgz"
      [[ ! -f "$win" ]] && wget --no-check-certificate https://files.verdehorizonte.net/api/public/dl/NHXSbLKY/windoze.tgz
      tar xzf "$win" -C /opt --checkpoint=.1000
      /opt/aevh/bin/windoze full
}

main "$@"
