#!/bin/bash
# Instalar o Windoze
# v1.5 2026-03-29

AEVH_LIB="/opt/aevh/lib/aevh-lib.sh"
[[ -f "$AEVH_LIB" ]] && source "$AEVH_LIB"
[[ "$AEVH_LIB_LOADED" != "1" ]] && { echo "Falha a carregar lib AEVH"; exit 1; }

main() {
    local distro
    distro="$(get_distro)"
    [[ "$distro" != "debian" ]] && log_critical "Este sistema não é Debian. Instalação cancelada."
    echo "Sistema Debian detetado."

    dst="/opt"
    src=windoze.tgz
    [[ ! -f "$src" ]] && log_critical "Não encontro $src"
    get_root
    mkdir -p "$dst"
    tar -xf "$src" -C "$dst" --checkpoint=.1000
    bash "$dst"/aevh/bin/windoze full
    bash "$dst"/aevh/bin/profile-menu
    confirm "Instalação concluída. É preciso reiniciar o sistema." "Reiniciar" && reboot
    echo "Reiniciar log que possível."
}

main "$@"
