#!/bin/bash
# v 1.2 2026-03-29

error() { echo "ERRO: $1"; exit 1; }

main() {
    local zip="-z" root="$HOME/git/windoze"
    [[ -d "$root" ]] || error "Diretoria não encontrada: root"

    command -v pigz &> /dev/null && zip="--use-compress-program=pigz -9 --rsyncable"
    pushd "$root" || error "Não consigo entrar em $root"
    [[ -d "$root/build/aevh" ]] && rm -rf "$root/build/aevh"
    mkdir -p "$root"/build/aevh/{bin,conf,static}
    cp -aR bin/* "$root"/build/aevh/bin/
    cp -aR conf/* "$root"/build/aevh/conf/
    cp -aR static/* "$root"/build/aevh/static/
    cd "$root"/build || error "Não consigo entrar em $root/build"
    tar "${zip}" -cvf windoze.tgz aevh/
    rm -rf aevh
    popd || error "Não consigo voltar à diretoria original"
}

main "$@"
